#ifndef ADE90XXREG_H
#define ADE90XXREG_H

#define ADE90xx_STR(s) #s

// LOW LEVEL
enum
RegisterAdd 
{
  ADE_ADD_AIGAIN   = 0x000,
  ADE_ADD_AIGAIN0,
  ADE_ADD_AIGAIN1,
  ADE_ADD_AIGAIN2,
  ADE_ADD_AIGAIN3,
  ADE_ADD_AIGAIN4,
  ADE_ADD_APHCAL0,
  ADE_ADD_APHCAL1,
  ADE_ADD_APHCAL2,
  ADE_ADD_APHCAL3,
  ADE_ADD_APHCAL4,
  ADE_ADD_AVGAIN,
  ADE_ADD_AIRMSOS,
  ADE_ADD_AVRMSOS,
  ADE_ADD_APGAIN,
  ADE_ADD_AWATTOS,
  ADE_ADD_AVAROS,
  ADE_ADD_AFWATTOS, // 78
  ADE_ADD_AFVAROS,
  ADE_ADD_AIFRMSOS, // 78
  ADE_ADD_AVFRMSOS, // 78
  ADE_ADD_AVRMSONEOS, // 78
  ADE_ADD_AIRMSONEOS, // 78
  ADE_ADD_AVRMS1012OS, // 78
  ADE_ADD_AIRMS1012OS, // 78
  ADE_ADD_BIGAIN = 0x20,
  ADE_ADD_BIGAIN0,
  ADE_ADD_BIGAIN1,
  ADE_ADD_BIGAIN2,
  ADE_ADD_BIGAIN3,
  ADE_ADD_BIGAIN4,
  ADE_ADD_BPHCAL0,
  ADE_ADD_BPHCAL1,
  ADE_ADD_BPHCAL2,
  ADE_ADD_BPHCAL3,
  ADE_ADD_BPHCAL4,
  ADE_ADD_BVGAIN,
  ADE_ADD_BIRMSOS,
  ADE_ADD_BVRMSOS,
  ADE_ADD_BPGAIN,
  ADE_ADD_BWATTOS,
  ADE_ADD_BVAROS,
  ADE_ADD_BFWATTOS, // 78
  ADE_ADD_BFVAROS,
  ADE_ADD_BIFRMSOS, // 78
  ADE_ADD_BVFRMSOS, // 78
  ADE_ADD_BVRMSONEOS, // 78
  ADE_ADD_BIRMSONEOS, // 78
  ADE_ADD_BVRMS1012OS, // 78
  ADE_ADD_BIRMS1012OS, // 78
  ADE_ADD_CIGAIN = 0x040,
  ADE_ADD_CIGAIN0,
  ADE_ADD_CIGAIN1,
  ADE_ADD_CIGAIN2,
  ADE_ADD_CIGAIN3,
  ADE_ADD_CIGAIN4,
  ADE_ADD_CPHCAL0,
  ADE_ADD_CPHCAL1,
  ADE_ADD_CPHCAL2,
  ADE_ADD_CPHCAL3,
  ADE_ADD_CPHCAL4,
  ADE_ADD_CVGAIN,
  ADE_ADD_CIRMSOS,
  ADE_ADD_CVRMSOS,
  ADE_ADD_CPGAIN,
  ADE_ADD_CWATTOS,
  ADE_ADD_CVAROS,
  ADE_ADD_CFWATTOS, // 78
  ADE_ADD_CFVAROS,
  ADE_ADD_CIFRMSOS, // 78
  ADE_ADD_CVFRMSOS, // 78
  ADE_ADD_CVRMSONEOS, // 78
  ADE_ADD_CIRMSONEOS, // 78
  ADE_ADD_CVRMS1012OS, // 78
  ADE_ADD_CIRMS1012OS, // 78
  ADE_ADD_CONFIG0 = 0x060,
  ADE_ADD_MTTHR_L0,
  ADE_ADD_MTTHR_L1,
  ADE_ADD_MTTHR_L2,
  ADE_ADD_MTTHR_L3,
  ADE_ADD_MTTHR_L4,
  ADE_ADD_MTTHR_H0,
  ADE_ADD_MTTHR_H1,
  ADE_ADD_MTTHR_H2,
  ADE_ADD_MTTHR_H3,
  ADE_ADD_MTTHR_H4,
  ADE_ADD_NIRMSOS,
  ADE_ADD_ISUMRMSOS,
  ADE_ADD_NIGAIN,
  ADE_ADD_NPHCAL,
  ADE_ADD_NIRMSONEOS, // 78
  ADE_ADD_NIRMS1012OS, // 78
  ADE_ADD_VNOM,
  ADE_ADD_DICOEFF,
  ADE_ADD_ISUMLVL,
  ADE_ADD_AI_PCF = 0x20A,
  ADE_ADD_AV_PCF,
  ADE_ADD_AIRMS,
  ADE_ADD_AVRMS,
  ADE_ADD_AIFRMS, // 78
  ADE_ADD_AVFRMS, // 78
  ADE_ADD_AWATT,
  ADE_ADD_AVAR,
  ADE_ADD_AVA,
  ADE_ADD_AFWATT, // 78
  ADE_ADD_AFVAR,
  ADE_ADD_AFVA, // 78
  ADE_ADD_APF,
  ADE_ADD_AVTHD, // 78
  ADE_ADD_AITHD, // 78
  ADE_ADD_AIRMSONE, // 78
  ADE_ADD_AVRMSONE, // 78
  ADE_ADD_AIRMS1012, // 78
  ADE_ADD_AVRMS1012, // 78
  ADE_ADD_AMTREGION,
  ADE_ADD_BI_PCF = 0x22A,
  ADE_ADD_BV_PCF,
  ADE_ADD_BIRMS,
  ADE_ADD_BVRMS,
  ADE_ADD_BIFRMS, // 78
  ADE_ADD_BVFRMS, // 78
  ADE_ADD_BWATT,
  ADE_ADD_BVAR,
  ADE_ADD_BVA,
  ADE_ADD_BFWATT, // 78
  ADE_ADD_BFVAR,
  ADE_ADD_BFVA, // 78
  ADE_ADD_BPF,
  ADE_ADD_BVTHD, // 78
  ADE_ADD_BITHD, // 78
  ADE_ADD_BIRMSONE, // 78
  ADE_ADD_BVRMSONE, // 78
  ADE_ADD_BIRMS1012, // 78
  ADE_ADD_BVRMS1012, // 78
  ADE_ADD_BMTREGION,
  ADE_ADD_CI_PCF = 0x24A,
  ADE_ADD_CV_PCF,
  ADE_ADD_CIRMS,
  ADE_ADD_CVRMS,
  ADE_ADD_CIFRMS, // 78
  ADE_ADD_CVFRMS, // 78
  ADE_ADD_CWATT,
  ADE_ADD_CVAR,
  ADE_ADD_CVA,
  ADE_ADD_CFWATT, // 78
  ADE_ADD_CFVAR,
  ADE_ADD_CFVA, // 78
  ADE_ADD_CPF,
  ADE_ADD_CVTHD, // 78
  ADE_ADD_CITHD, // 78
  ADE_ADD_CIRMSONE, // 78
  ADE_ADD_CVRMSONE, // 78
  ADE_ADD_CIRMS1012, // 78
  ADE_ADD_CVRMS1012, // 78
  ADE_ADD_CMTREGION,
  ADE_ADD_NI_PCF = 0x265,
  ADE_ADD_NIRMS,
  ADE_ADD_NIRMSONE, // 78
  ADE_ADD_NIRMS1012, // 78
  ADE_ADD_ISUMRMS,
  ADE_ADD_VERSION2,
  ADE_ADD_AWATT_ACC = 0x2E5,
  ADE_ADD_AWATTHR_LO,
  ADE_ADD_AWATTHR_HI,
  ADE_ADD_AVAR_ACC = 0x2EF,
  ADE_ADD_AVARHR_LO,
  ADE_ADD_AVARHR_HI,
  ADE_ADD_AVA_ACC = 0x2F9,
  ADE_ADD_AVAHR_LO,
  ADE_ADD_AVAHR_HI,
  ADE_ADD_AFWATT_ACC = 0x303, // 78
  ADE_ADD_AFWATTHR_LO, // 78
  ADE_ADD_AFWATTHR_HI, // 78
  ADE_ADD_AFVAR_ACC = 0x30D,
  ADE_ADD_AFVARHR_LO,
  ADE_ADD_AFVARHR_HI,
  ADE_ADD_AFVA_ACC = 0x317, // 78
  ADE_ADD_AFVAHR_LO, // 78
  ADE_ADD_AFVAHR_HI, // 78
  ADE_ADD_BWATT_ACC = 0x321,
  ADE_ADD_BWATTHR_LO,
  ADE_ADD_BWATTHR_HI,
  ADE_ADD_BVAR_ACC = 0x32B,
  ADE_ADD_BVARHR_LO,
  ADE_ADD_BVARHR_HI,
  ADE_ADD_BVA_ACC = 0x335,
  ADE_ADD_BVAHR_LO,
  ADE_ADD_BVAHR_HI,
  ADE_ADD_BFWATT_ACC = 0x33F, // 78
  ADE_ADD_BFWATTHR_LO, // 78
  ADE_ADD_BFWATTHR_HI, // 78
  ADE_ADD_BFVAR_ACC = 0x34F,
  ADE_ADD_BFVARHR_LO,
  ADE_ADD_BFVARHR_HI,
  ADE_ADD_BFVA_ACC = 0x353, // 78
  ADE_ADD_BFVAHR_LO, // 78
  ADE_ADD_BFVAHR_HI, // 78
  ADE_ADD_CWATT_ACC = 0x35D,
  ADE_ADD_CWATTHR_LO,
  ADE_ADD_CWATTHR_HI,
  ADE_ADD_CVAR_ACC = 0x367,
  ADE_ADD_CVARHR_LO,
  ADE_ADD_CVARHR_HI,
  ADE_ADD_CVA_ACC = 0x371,
  ADE_ADD_CVAHR_LO,
  ADE_ADD_CVAHR_HI,
  ADE_ADD_CFWATT_ACC = 0x37B, // 78
  ADE_ADD_CFWATTHR_LO, // 78
  ADE_ADD_CFWATTHR_HI, // 78
  ADE_ADD_CFVAR_ACC = 0x385,
  ADE_ADD_CFVARHR_LO,
  ADE_ADD_CFVARHR_HI,
  ADE_ADD_CFVA_ACC = 0x38F, // 78
  ADE_ADD_CFVAHR_LO, // 78
  ADE_ADD_CFVAHR_HI, // 78
  ADE_ADD_PWATT_ACC = 0x397,
  ADE_ADD_NWATT_ACC = 0x39B,
  ADE_ADD_PVAR_ACC = 0x39F,
  ADE_ADD_NVAR_ACC = 0x3A3,
  ADE_ADD_IPEAK = 0x400,
  ADE_ADD_VPEAK,
  ADE_ADD_STATUS0,
  ADE_ADD_STATUS1,
  ADE_ADD_EVENT_STATUS,
  ADE_ADD_MASK0,
  ADE_ADD_MASK1,
  ADE_ADD_EVENT_MASK,
  ADE_ADD_OILVL = 0x409, // 78
  ADE_ADD_OIA, // 78
  ADE_ADD_OIB, // 78
  ADE_ADD_OIC, // 78
  ADE_ADD_OIN, // 78
  ADE_ADD_USER_PERIOD,
  ADE_ADD_VLEVEL,
  ADE_ADD_DIP_LVL, // 78
  ADE_ADD_DIPA, // 78
  ADE_ADD_DIPB, // 78
  ADE_ADD_DIPC, // 78
  ADE_ADD_SWELL_LVL, // 78
  ADE_ADD_SWELLA, // 78
  ADE_ADD_SWELLB, // 78
  ADE_ADD_SWELLC, // 78
  ADE_ADD_APERIOD,
  ADE_ADD_BPERIOD,
  ADE_ADD_CPERIOD,
  ADE_ADD_COM_PERIOD,
  ADE_ADD_ACT_NL_LVL,
  ADE_ADD_REACT_NL_LVL,
  ADE_ADD_APP_NL_LVL,
  ADE_ADD_PHNOLOAD,
  ADE_ADD_WTHR,
  ADE_ADD_VARTHR,
  ADE_ADD_VATHR,
  ADE_ADD_LAST_DATA_32,
  ADE_ADD_ADC_REDIRECT,
  ADE_ADD_CF_LCFG,
  ADE_ADD_PART_ID = 0x472,
  ADE_ADD_TEMP_TRIM = 0x474, // 78
  ADE_ADD_RUN = 0x480,
  ADE_ADD_CONFIG1,
  ADE_ADD_ANGL_VA_VB,
  ADE_ADD_ANGL_VB_VC,
  ADE_ADD_ANGL_VA_VC,
  ADE_ADD_ANGL_VA_IA,
  ADE_ADD_ANGL_VB_IB,
  ADE_ADD_ANGL_VC_IC,
  ADE_ADD_ANGL_IA_IB,
  ADE_ADD_ANGL_IB_IC,
  ADE_ADD_ANGL_IA_IC,
  ADE_ADD_DIP_CYC, // 78
  ADE_ADD_SWELL_CYC, // 78
  ADE_ADD_OISTATUS = 0x48F, // 78
  ADE_ADD_CFMODE,
  ADE_ADD_COMPMODE,
  ADE_ADD_ACCMODE,
  ADE_ADD_CONFIG3,
  ADE_ADD_CF1DEN,
  ADE_ADD_CF2DEN,
  ADE_ADD_CF3DEN,
  ADE_ADD_CF4DEN,
  ADE_ADD_ZXTOUT,
  ADE_ADD_ZXTHRSH,
  ADE_ADD_ZX_LP_SEL,
  ADE_ADD_SEQ_CYC = 0x49C,
  ADE_ADD_PHSIGN,
  ADE_ADD_WFB_CFG = 0x4A0,
  ADE_ADD_WFB_PG_IRQEN,
  ADE_ADD_WFB_TRG_CFG,
  ADE_ADD_WFB_TRG_STAT,
  ADE_ADD_CONFIG5,
  ADE_ADD_CRC_RSLT = 0x4A8,
  ADE_ADD_CRC_SPI,
  ADE_ADD_LAST_DATA_16 = 0x4AC,
  ADE_ADD_LAST_CMD = 0x4AE,
  ADE_ADD_CONFIG2,
  ADE_ADD_EP_CFG,
  ADE_ADD_PWR_TIME,
  ADE_ADD_EGY_TIME,
  ADE_ADD_CRC_FORCE = 0x4B4,
  ADE_ADD_CRC_OPTEN,
  ADE_ADD_TEMP_CFG, // 78
  ADE_ADD_TEMP_RSLT, // 78
  ADE_ADD_PSM2_CFG = 0x4B8, // 00
  ADE_ADD_PGA_GAIN,
  ADE_ADD_CHNL_DIS,
  ADE_ADD_WR_LOCK = 0x4BF,
  ADE_ADD_VAR_DIS = 0x4E0,
  ADE_ADD_RESERVED1 = 0x4F0,
  ADE_ADD_VERSION = 0x4FE,
  ADE_ADD_AI_SINC_DAT = 0x500,
  ADE_ADD_AV_SINC_DAT,
  ADE_ADD_BI_SINC_DAT,
  ADE_ADD_BV_SINC_DAT,
  ADE_ADD_CI_SINC_DAT,
  ADE_ADD_CV_SINC_DAT,
  ADE_ADD_NI_SINC_DAT,
  ADE_ADD_AI_LPF_DAT = 0x510,
  ADE_ADD_AV_LPF_DAT,
  ADE_ADD_BI_LPF_DAT,
  ADE_ADD_BV_LPF_DAT,
  ADE_ADD_CI_LPF_DAT,
  ADE_ADD_CV_LPF_DAT,
  ADE_ADD_NI_LPF_DAT,
  ADE_ADD_AV_PCF_1 = 0x600,
  ADE_ADD_BV_PCF_1,
  ADE_ADD_CV_PCF_1,
  ADE_ADD_NI_PCF_1,
  ADE_ADD_AI_PCF_1,
  ADE_ADD_BI_PCF_1,
  ADE_ADD_CI_PCF_1,
  ADE_ADD_AIRMS_1,
  ADE_ADD_BIRMS_1,
  ADE_ADD_CIRMS_1,
  ADE_ADD_AVRMS_1,
  ADE_ADD_BVRMS_1,
  ADE_ADD_CVRMS_1,
  ADE_ADD_NIRMS_1,
  ADE_ADD_AWATT_1,
  ADE_ADD_BWATT_1,
  ADE_ADD_CWATT_1,
  ADE_ADD_AVA_1,
  ADE_ADD_BVA_1,
  ADE_ADD_CVA_1,
  ADE_ADD_AVAR_1,
  ADE_ADD_BVAR_1,
  ADE_ADD_CVAR_1,
  ADE_ADD_AFVAR_1,
  ADE_ADD_BFVAR_1,
  ADE_ADD_CFVAR_1,
  ADE_ADD_APF_1,
  ADE_ADD_BPF_1,
  ADE_ADD_CPF_1,
  ADE_ADD_AVTHD_1, // 78
  ADE_ADD_BVTHD_1, // 78
  ADE_ADD_CVTHD_1, // 78
  ADE_ADD_AITHD_1, // 78
  ADE_ADD_BITHD_1, // 78
  ADE_ADD_CITHD_1, // 78
  ADE_ADD_AFWATT_1, // 78
  ADE_ADD_BFWATT_1, // 78
  ADE_ADD_CFWATT_1, // 78
  ADE_ADD_AFVA_1, // 78
  ADE_ADD_BFVA_1, // 78
  ADE_ADD_CFVA_1, // 78
  ADE_ADD_AFIRMS_1, // 78
  ADE_ADD_BFIRMS_1, // 78
  ADE_ADD_CFIRMS_1, // 78
  ADE_ADD_AFVRMS_1, // 78
  ADE_ADD_BFVRMS_1, // 78
  ADE_ADD_CFVRMS_1, // 78
  ADE_ADD_AIRMSONE_1, // 78
  ADE_ADD_BIRMSONE_1, // 78
  ADE_ADD_CIRMSONE_1, // 78
  ADE_ADD_AVRMSONE_1, // 78
  ADE_ADD_BVRMSONE_1, // 78
  ADE_ADD_CVRMSONE_1, // 78
  ADE_ADD_NIRMSONE_1, // 78
  ADE_ADD_AIRMS1012_1, // 78
  ADE_ADD_BIRMS1012_1, // 78
  ADE_ADD_CIRMS1012_1, // 78
  ADE_ADD_AVRMS1012_1, // 78
  ADE_ADD_BVRMS1012_1, // 78
  ADE_ADD_CVRMS1012_1, // 78
  ADE_ADD_NIRMS1012_1, // 78
  ADE_ADD_AV_PCF_2 = 0x680,
  ADE_ADD_AI_PCF_2,
  ADE_ADD_AIRMS_2,
  ADE_ADD_AVRMS_2,
  ADE_ADD_AWATT_2,
  ADE_ADD_AVA_2,
  ADE_ADD_AVAR_2,
  ADE_ADD_AFVAR_2,
  ADE_ADD_APF_2,
  ADE_ADD_AVTHD_2, // 78
  ADE_ADD_AITHD_2, // 78
  ADE_ADD_AFWATT_2, // 78
  ADE_ADD_AFVA_2, // 78
  ADE_ADD_AFIRMS_2, // 78
  ADE_ADD_AFVRMS_2, // 78
  ADE_ADD_AIRMSONE_2, // 78
  ADE_ADD_AVRMSONE_2, // 78
  ADE_ADD_AIRMS1012_2, // 78
  ADE_ADD_AVRMS1012_2, // 78
  ADE_ADD_BV_PCF_2,
  ADE_ADD_BI_PCF_2,
  ADE_ADD_BIRMS_2,
  ADE_ADD_BVRMS_2,
  ADE_ADD_BWATT_2,
  ADE_ADD_BVA_2,
  ADE_ADD_BVAR_2,
  ADE_ADD_BFVAR_2,
  ADE_ADD_BPF_2,
  ADE_ADD_BVTHD_2, // 78
  ADE_ADD_BITHD_2, // 78
  ADE_ADD_BFWATT_2, // 78
  ADE_ADD_BFVA_2, // 78
  ADE_ADD_BFIRMS_2, // 78
  ADE_ADD_BFVRMS_2, // 78
  ADE_ADD_BIRMSONE_2, // 78
  ADE_ADD_BVRMSONE_2, // 78
  ADE_ADD_BIRMS1012_2, // 78
  ADE_ADD_BVRMS1012_2, // 78
  ADE_ADD_CV_PCF_2,
  ADE_ADD_CI_PCF_2,
  ADE_ADD_CIRMS_2,
  ADE_ADD_CVRMS_2,
  ADE_ADD_CWATT_2,
  ADE_ADD_CVA_2,
  ADE_ADD_CVAR_2,
  ADE_ADD_CFVAR_2,
  ADE_ADD_CPF_2,
  ADE_ADD_CVTHD_2, // 78
  ADE_ADD_CITHD_2, // 78
  ADE_ADD_CFWATT_2, // 78
  ADE_ADD_CFVA_2, // 78
  ADE_ADD_CFIRMS_2, // 78
  ADE_ADD_CFVRMS_2, // 78
  ADE_ADD_CIRMSONE_2, // 78
  ADE_ADD_CVRMSONE_2, // 78
  ADE_ADD_CIRMS1012_2, // 78
  ADE_ADD_CVRMS1012_2, // 78
  ADE_ADD_NI_PCF_2,
  ADE_ADD_NIRMS_2,
  ADE_ADD_NIRMSONE_2, // 78
  ADE_ADD_NIRMS1012_2 // 78
};

enum
RegisterSize 
{
  ADE_SIZE_AIGAIN = 32,
  ADE_SIZE_AIGAIN0 = 32,
  ADE_SIZE_AIGAIN1 = 32,
  ADE_SIZE_AIGAIN2 = 32,
  ADE_SIZE_AIGAIN3 = 32,
  ADE_SIZE_AIGAIN4 = 32,
  ADE_SIZE_APHCAL0 = 32,
  ADE_SIZE_APHCAL1 = 32,
  ADE_SIZE_APHCAL2 = 32,
  ADE_SIZE_APHCAL3 = 32,
  ADE_SIZE_APHCAL4 = 32,
  ADE_SIZE_AVGAIN = 32,
  ADE_SIZE_AIRMSOS = 32,
  ADE_SIZE_AVRMSOS = 32,
  ADE_SIZE_APGAIN = 32,
  ADE_SIZE_AWATTOS = 32,
  ADE_SIZE_AVAROS = 32,
  ADE_SIZE_AFWATTOS = 32, // 78
  ADE_SIZE_AFVAROS = 32,
  ADE_SIZE_AIFRMSOS = 32, // 78
  ADE_SIZE_AVFRMSOS = 32, // 78
  ADE_SIZE_AVRMSONEOS = 32, // 78
  ADE_SIZE_AIRMSONEOS = 32, // 78
  ADE_SIZE_AVRMS1012OS = 32, // 78
  ADE_SIZE_AIRMS1012OS = 32, // 78
  ADE_SIZE_BIGAIN = 32,
  ADE_SIZE_BIGAIN0 = 32,
  ADE_SIZE_BIGAIN1 = 32,
  ADE_SIZE_BIGAIN2 = 32,
  ADE_SIZE_BIGAIN3 = 32,
  ADE_SIZE_BIGAIN4 = 32,
  ADE_SIZE_BPHCAL0 = 32,
  ADE_SIZE_BPHCAL1 = 32,
  ADE_SIZE_BPHCAL2 = 32,
  ADE_SIZE_BPHCAL3 = 32,
  ADE_SIZE_BPHCAL4 = 32,
  ADE_SIZE_BVGAIN = 32,
  ADE_SIZE_BIRMSOS = 32,
  ADE_SIZE_BVRMSOS = 32,
  ADE_SIZE_BPGAIN = 32,
  ADE_SIZE_BWATTOS = 32,
  ADE_SIZE_BVAROS = 32,
  ADE_SIZE_BFWATTOS = 32, // 78
  ADE_SIZE_BFVAROS = 32,
  ADE_SIZE_BIFRMSOS = 32, // 78
  ADE_SIZE_BVFRMSOS = 32, // 78
  ADE_SIZE_BVRMSONEOS = 32, // 78
  ADE_SIZE_BIRMSONEOS = 32, // 78
  ADE_SIZE_BVRMS1012OS = 32, // 78
  ADE_SIZE_BIRMS1012OS = 32, // 78
  ADE_SIZE_CIGAIN = 32,
  ADE_SIZE_CIGAIN0 = 32,
  ADE_SIZE_CIGAIN1 = 32,
  ADE_SIZE_CIGAIN2 = 32,
  ADE_SIZE_CIGAIN3 = 32,
  ADE_SIZE_CIGAIN4 = 32,
  ADE_SIZE_CPHCAL0 = 32,
  ADE_SIZE_CPHCAL1 = 32,
  ADE_SIZE_CPHCAL2 = 32,
  ADE_SIZE_CPHCAL3 = 32,
  ADE_SIZE_CPHCAL4 = 32,
  ADE_SIZE_CVGAIN = 32,
  ADE_SIZE_CIRMSOS = 32,
  ADE_SIZE_CVRMSOS = 32,
  ADE_SIZE_CPGAIN = 32,
  ADE_SIZE_CWATTOS = 32,
  ADE_SIZE_CVAROS = 32,
  ADE_SIZE_CFWATTOS = 32, // 78
  ADE_SIZE_CFVAROS = 32,
  ADE_SIZE_CIFRMSOS = 32, // 78
  ADE_SIZE_CVFRMSOS = 32, // 78
  ADE_SIZE_CVRMSONEOS = 32, // 78
  ADE_SIZE_CIRMSONEOS = 32, // 78
  ADE_SIZE_CVRMS1012OS = 32, // 78
  ADE_SIZE_CIRMS1012OS = 32, // 78
  ADE_SIZE_CONFIG0 = 32,
  ADE_SIZE_MTTHR_L0 = 32,
  ADE_SIZE_MTTHR_L1 = 32,
  ADE_SIZE_MTTHR_L2 = 32,
  ADE_SIZE_MTTHR_L3 = 32,
  ADE_SIZE_MTTHR_L4 = 32,
  ADE_SIZE_MTTHR_H0 = 32,
  ADE_SIZE_MTTHR_H1 = 32,
  ADE_SIZE_MTTHR_H2 = 32,
  ADE_SIZE_MTTHR_H3 = 32,
  ADE_SIZE_MTTHR_H4 = 32,
  ADE_SIZE_NIRMSOS = 32,
  ADE_SIZE_ISUMRMSOS = 32,
  ADE_SIZE_NIGAIN = 32,
  ADE_SIZE_NPHCAL = 32,
  ADE_SIZE_NIRMSONEOS = 32, // 78
  ADE_SIZE_NIRMS1012OS = 32, // 78
  ADE_SIZE_VNOM = 32,
  ADE_SIZE_DICOEFF = 32,
  ADE_SIZE_ISUMLVL = 32,
  ADE_SIZE_AI_PCF = 32,
  ADE_SIZE_AV_PCF = 32,
  ADE_SIZE_AIRMS = 32,
  ADE_SIZE_AVRMS = 32,
  ADE_SIZE_AIFRMS = 32, // 78
  ADE_SIZE_AVFRMS = 32, // 78
  ADE_SIZE_AWATT = 32,
  ADE_SIZE_AVAR = 32,
  ADE_SIZE_AVA = 32,
  ADE_SIZE_AFWATT = 32, // 78
  ADE_SIZE_AFVAR = 32,
  ADE_SIZE_AFVA = 32, // 78
  ADE_SIZE_APF = 32,
  ADE_SIZE_AVTHD = 32, // 78
  ADE_SIZE_AITHD = 32, // 78
  ADE_SIZE_AIRMSONE = 32, // 78
  ADE_SIZE_AVRMSONE = 32, // 78
  ADE_SIZE_AIRMS1012 = 32, // 78
  ADE_SIZE_AVRMS1012 = 32, // 78
  ADE_SIZE_AMTREGION = 32,
  ADE_SIZE_BI_PCF = 32,
  ADE_SIZE_BV_PCF = 32,
  ADE_SIZE_BIRMS = 32,
  ADE_SIZE_BVRMS = 32,
  ADE_SIZE_BIFRMS = 32, // 78
  ADE_SIZE_BVFRMS = 32, // 78
  ADE_SIZE_BWATT = 32,
  ADE_SIZE_BVAR = 32,
  ADE_SIZE_BVA = 32,
  ADE_SIZE_BFWATT = 32, // 78
  ADE_SIZE_BFVAR = 32,
  ADE_SIZE_BFVA = 32, // 78
  ADE_SIZE_BPF = 32,
  ADE_SIZE_BVTHD = 32, // 78
  ADE_SIZE_BITHD = 32, // 78
  ADE_SIZE_BIRMSONE = 32, // 78
  ADE_SIZE_BVRMSONE = 32, // 78
  ADE_SIZE_BIRMS1012 = 32, // 78
  ADE_SIZE_BVRMS1012 = 32, // 78
  ADE_SIZE_BMTREGION = 32,
  ADE_SIZE_CI_PCF = 32,
  ADE_SIZE_CV_PCF = 32,
  ADE_SIZE_CIRMS = 32,
  ADE_SIZE_CVRMS = 32,
  ADE_SIZE_CIFRMS = 32, // 78
  ADE_SIZE_CVFRMS = 32, // 78
  ADE_SIZE_CWATT = 32,
  ADE_SIZE_CVAR = 32,
  ADE_SIZE_CVA = 32,
  ADE_SIZE_CFWATT = 32, // 78
  ADE_SIZE_CFVAR = 32,
  ADE_SIZE_CFVA = 32, // 78
  ADE_SIZE_CPF = 32,
  ADE_SIZE_CVTHD = 32, // 78
  ADE_SIZE_CITHD = 32, // 78
  ADE_SIZE_CIRMSONE = 32, // 78
  ADE_SIZE_CVRMSONE = 32, // 78
  ADE_SIZE_CIRMS1012 = 32, // 78
  ADE_SIZE_CVRMS1012 = 32, // 78
  ADE_SIZE_CMTREGION = 32,
  ADE_SIZE_NI_PCF = 32,
  ADE_SIZE_NIRMS = 32,
  ADE_SIZE_NIRMSONE = 32, // 78
  ADE_SIZE_NIRMS1012 = 32, // 78
  ADE_SIZE_ISUMRMS = 32,
  ADE_SIZE_VERSION2 = 32,
  ADE_SIZE_AWATT_ACC = 32,
  ADE_SIZE_AWATTHR_LO = 32,
  ADE_SIZE_AWATTHR_HI = 32,
  ADE_SIZE_AVAR_ACC = 32,
  ADE_SIZE_AVARHR_LO = 32,
  ADE_SIZE_AVARHR_HI = 32,
  ADE_SIZE_AVA_ACC = 32,
  ADE_SIZE_AVAHR_LO = 32,
  ADE_SIZE_AVAHR_HI = 32,
  ADE_SIZE_AFWATT_ACC = 32, // 78
  ADE_SIZE_AFWATTHR_LO = 32, // 78
  ADE_SIZE_AFWATTHR_HI = 32, // 78
  ADE_SIZE_AFVAR_ACC = 32,
  ADE_SIZE_AFVARHR_LO = 32,
  ADE_SIZE_AFVARHR_HI = 32,
  ADE_SIZE_AFVA_ACC = 32, // 78
  ADE_SIZE_AFVAHR_LO = 32, // 78
  ADE_SIZE_AFVAHR_HI = 32, // 78
  ADE_SIZE_BWATT_ACC = 32,
  ADE_SIZE_BWATTHR_LO = 32,
  ADE_SIZE_BWATTHR_HI = 32,
  ADE_SIZE_BVAR_ACC = 32,
  ADE_SIZE_BVARHR_LO = 32,
  ADE_SIZE_BVARHR_HI = 32,
  ADE_SIZE_BVA_ACC = 32,
  ADE_SIZE_BVAHR_LO = 32,
  ADE_SIZE_BVAHR_HI = 32,
  ADE_SIZE_BFWATT_ACC = 32, // 78
  ADE_SIZE_BFWATTHR_LO = 32, // 78
  ADE_SIZE_BFWATTHR_HI = 32, // 78
  ADE_SIZE_BFVAR_ACC = 32,
  ADE_SIZE_BFVARHR_LO = 32,
  ADE_SIZE_FVARHR_HI = 32,
  ADE_SIZE_BFVA_ACC = 32, // 78
  ADE_SIZE_BFVAHR_LO = 32, // 78
  ADE_SIZE_BFVAHR_HI = 32, // 78
  ADE_SIZE_CWATT_ACC = 32,
  ADE_SIZE_CWATTHR_LO = 32,
  ADE_SIZE_CWATTHR_HI = 32,
  ADE_SIZE_CVAR_ACC = 32,
  ADE_SIZE_CVARHR_LO = 32,
  ADE_SIZE_CVARHR_HI = 32,
  ADE_SIZE_CVA_ACC = 32,
  ADE_SIZE_CVAHR_LO = 32,
  ADE_SIZE_CVAHR_HI = 32,
  ADE_SIZE_CFWATT_ACC = 32, // 78
  ADE_SIZE_CFWATTHR_LO = 32, // 78
  ADE_SIZE_CFWATTHR_HI = 32, // 78
  ADE_SIZE_CFVAR_ACC = 32,
  ADE_SIZE_CFVARHR_LO = 32,
  ADE_SIZE_CFVARHR_HI = 32,
  ADE_SIZE_CFVA_ACC = 32, // 78
  ADE_SIZE_CFVAHR_LO = 32, // 78
  ADE_SIZE_CFVAHR_HI = 32, // 78
  ADE_SIZE_PWATT_ACC = 32,
  ADE_SIZE_NWATT_ACC = 32,
  ADE_SIZE_PVAR_ACC = 32,
  ADE_SIZE_NVAR_ACC = 32,
  ADE_SIZE_IPEAK = 32,
  ADE_SIZE_VPEAK = 32,
  ADE_SIZE_STATUS0 = 32,
  ADE_SIZE_STATUS1 = 32,
  ADE_SIZE_EVENT_STATUS = 32,
  ADE_SIZE_MASK0 = 32,
  ADE_SIZE_MASK1 = 32,
  ADE_SIZE_EVENT_MASK = 32,
  ADE_SIZE_OILVL = 32, // 78
  ADE_SIZE_OIA = 32, // 78
  ADE_SIZE_OIB = 32, // 78
  ADE_SIZE_OIC = 32, // 78
  ADE_SIZE_OIN = 32, // 78
  ADE_SIZE_USER_PERIOD = 32,
  ADE_SIZE_VLEVEL = 32,
  ADE_SIZE_DIP_LVL = 32, // 78
  ADE_SIZE_DIPA = 32, // 78
  ADE_SIZE_DIPB = 32, // 78
  ADE_SIZE_DIPC = 32, // 78
  ADE_SIZE_SWELL_LVL = 32, // 78
  ADE_SIZE_SWELLA = 32, // 78
  ADE_SIZE_SWELLB = 32, // 78
  ADE_SIZE_SWELLC = 32, // 78
  ADE_SIZE_APERIOD = 32,
  ADE_SIZE_BPERIOD = 32,
  ADE_SIZE_CPERIOD = 32,
  ADE_SIZE_COM_PERIOD = 32,
  ADE_SIZE_ACT_NL_LVL = 32,
  ADE_SIZE_REACT_NL_LVL = 32,
  ADE_SIZE_APP_NL_LVL = 32,
  ADE_SIZE_PHNOLOAD = 32,
  ADE_SIZE_WTHR = 32,
  ADE_SIZE_VARTHR = 32,
  ADE_SIZE_VATHR = 32,
  ADE_SIZE_LAST_DATA_32 = 32,
  ADE_SIZE_ADC_REDIRECT = 32,
  ADE_SIZE_CF_LCFG = 32,
  ADE_SIZE_PART_ID = 32,
  ADE_SIZE_TEMP_TRIM = 16, // 78
  ADE_SIZE_RUN = 16,
  ADE_SIZE_CONFIG1 = 16,
  ADE_SIZE_ANGL_VA_VB = 16,
  ADE_SIZE_ANGL_VB_VC = 16,
  ADE_SIZE_ANGL_VA_VC = 16,
  ADE_SIZE_ANGL_VA_IA = 16,
  ADE_SIZE_ANGL_VB_IB = 16,
  ADE_SIZE_ANGL_VC_IC = 16,
  ADE_SIZE_ANGL_IA_IB = 16,
  ADE_SIZE_ANGL_IB_IC = 16,
  ADE_SIZE_ANGL_IA_IC = 16,
  ADE_SIZE_DIP_CYC = 16, // 78
  ADE_SIZE_SWELL_CYC = 16, // 78
  ADE_SIZE_OISTATUS = 16, // 78
  ADE_SIZE_CFMODE = 16,
  ADE_SIZE_COMPMODE = 16,
  ADE_SIZE_ACCMODE = 16,
  ADE_SIZE_CONFIG3 = 16,
  ADE_SIZE_CF1DEN = 16,
  ADE_SIZE_CF2DEN = 16,
  ADE_SIZE_CF3DEN = 16,
  ADE_SIZE_CF4DEN = 16,
  ADE_SIZE_ZXTOUT = 16,
  ADE_SIZE_ZXTHRSH = 16,
  ADE_SIZE_ZX_LP_SEL = 16,
  ADE_SIZE_SEQ_CYC = 16,
  ADE_SIZE_PHSIGN = 16,
  ADE_SIZE_WFB_CFG = 16,
  ADE_SIZE_WFB_PG_IRQEN = 16,
  ADE_SIZE_WFB_TRG_CFG = 16,
  ADE_SIZE_WFB_TRG_STAT = 16,
  ADE_SIZE_CONFIG5 = 16,
  ADE_SIZE_CRC_RSLT = 16,
  ADE_SIZE_CRC_SPI = 16,
  ADE_SIZE_LAST_DATA_16 = 16,
  ADE_SIZE_LAST_CMD = 16,
  ADE_SIZE_CONFIG2 = 16,
  ADE_SIZE_EP_CFG = 16,
  ADE_SIZE_PWR_TIME = 16,
  ADE_SIZE_EGY_TIME = 16,
  ADE_SIZE_CRC_FORCE = 16,
  ADE_SIZE_CRC_OPTEN = 16,
  ADE_SIZE_TEMP_CFG = 16, // 78
  ADE_SIZE_TEMP_RSLT = 16, // 78
  ADE_SIZE_PSM2_CFG = 16, // 00
  ADE_SIZE_PGA_GAIN = 16,
  ADE_SIZE_CHNL_DIS = 16,
  ADE_SIZE_WR_LOCK = 16,
  ADE_SIZE_VAR_DIS = 16,
  ADE_SIZE_RESERVED1 = 16,
  ADE_SIZE_VERSION = 16,
  ADE_SIZE_AI_SINC_DAT = 32,
  ADE_SIZE_AV_SINC_DAT = 32,
  ADE_SIZE_BI_SINC_DAT = 32,
  ADE_SIZE_BV_SINC_DAT = 32,
  ADE_SIZE_CI_SINC_DAT = 32,
  ADE_SIZE_CV_SINC_DAT = 32,
  ADE_SIZE_NI_SINC_DAT = 32,
  ADE_SIZE_AI_LPF_DAT = 32,
  ADE_SIZE_AV_LPF_DAT = 32,
  ADE_SIZE_BI_LPF_DAT = 32,
  ADE_SIZE_BV_LPF_DAT = 32,
  ADE_SIZE_CI_LPF_DAT = 32,
  ADE_SIZE_CV_LPF_DAT = 32,
  ADE_SIZE_NI_LPF_DAT = 32,
  ADE_SIZE_AV_PCF_1 = 32,
  ADE_SIZE_BV_PCF_1 = 32,
  ADE_SIZE_CV_PCF_1 = 32,
  ADE_SIZE_NI_PCF_1 = 32,
  ADE_SIZE_AI_PCF_1 = 32,
  ADE_SIZE_BI_PCF_1 = 32,
  ADE_SIZE_CI_PCF_1 = 32,
  ADE_SIZE_AIRMS_1 = 32,
  ADE_SIZE_BIRMS_1 = 32,
  ADE_SIZE_CIRMS_1 = 32,
  ADE_SIZE_AVRMS_1 = 32,
  ADE_SIZE_BVRMS_1 = 32,
  ADE_SIZE_CVRMS_1 = 32,
  ADE_SIZE_NIRMS_1 = 32,
  ADE_SIZE_AWATT_1 = 32,
  ADE_SIZE_BWATT_1 = 32,
  ADE_SIZE_CWATT_1 = 32,
  ADE_SIZE_AVA_1 = 32,
  ADE_SIZE_BVA_1 = 32,
  ADE_SIZE_CVA_1 = 32,
  ADE_SIZE_AVAR_1 = 32,
  ADE_SIZE_BVAR_1 = 32,
  ADE_SIZE_CVAR_1 = 32,
  ADE_SIZE_AFVAR_1 = 32,
  ADE_SIZE_BFVAR_1 = 32,
  ADE_SIZE_CFVAR_1 = 32,
  ADE_SIZE_APF_1 = 32,
  ADE_SIZE_BPF_1 = 32,
  ADE_SIZE_CPF_1 = 32,
  ADE_SIZE_AVTHD_1 = 32, // 78
  ADE_SIZE_BVTHD_1 = 32, // 78
  ADE_SIZE_CVTHD_1 = 32, // 78
  ADE_SIZE_AITHD_1 = 32, // 78
  ADE_SIZE_BITHD_1 = 32, // 78
  ADE_SIZE_CITHD_1 = 32, // 78
  ADE_SIZE_AFWATT_1 = 32, // 78
  ADE_SIZE_BFWATT_1 = 32, // 78
  ADE_SIZE_CFWATT_1 = 32, // 78
  ADE_SIZE_AFVA_1 = 32, // 78
  ADE_SIZE_BFVA_1 = 32, // 78
  ADE_SIZE_CFVA_1 = 32, // 78
  ADE_SIZE_AFIRMS_1 = 32, // 78
  ADE_SIZE_BFIRMS_1 = 32, // 78
  ADE_SIZE_CFIRMS_1 = 32, // 78
  ADE_SIZE_AFVRMS_1 = 32, // 78
  ADE_SIZE_BFVRMS_1 = 32, // 78
  ADE_SIZE_CFVRMS_1 = 32, // 78
  ADE_SIZE_AIRMSONE_1 = 32, // 78
  ADE_SIZE_BIRMSONE_1 = 32, // 78
  ADE_SIZE_CIRMSONE_1 = 32, // 78
  ADE_SIZE_AVRMSONE_1 = 32, // 78
  ADE_SIZE_BVRMSONE_1 = 32, // 78
  ADE_SIZE_CVRMSONE_1 = 32, // 78
  ADE_SIZE_NIRMSONE_1 = 32, // 78
  ADE_SIZE_AIRMS1012_1 = 32, // 78
  ADE_SIZE_BIRMS1012_1 = 32, // 78
  ADE_SIZE_CIRMS1012_1 = 32, // 78
  ADE_SIZE_AVRMS1012_1 = 32, // 78
  ADE_SIZE_BVRMS1012_1 = 32, // 78
  ADE_SIZE_CVRMS1012_1 = 32, // 78
  ADE_SIZE_NIRMS1012_1 = 32, // 78
  ADE_SIZE_AV_PCF_2 = 32,
  ADE_SIZE_AI_PCF_2 = 32,
  ADE_SIZE_AIRMS_2 = 32,
  ADE_SIZE_AVRMS_2 = 32,
  ADE_SIZE_AWATT_2 = 32,
  ADE_SIZE_AVA_2 = 32,
  ADE_SIZE_AVAR_2 = 32,
  ADE_SIZE_AFVAR_2 = 32,
  ADE_SIZE_APF_2 = 32,
  ADE_SIZE_AVTHD_2 = 32, // 78
  ADE_SIZE_AITHD_2 = 32, // 78
  ADE_SIZE_AFWATT_2 = 32, // 78
  ADE_SIZE_AFVA_2 = 32, // 78
  ADE_SIZE_AFIRMS_2 = 32, // 78
  ADE_SIZE_AFVRMS_2 = 32, // 78
  ADE_SIZE_AIRMSONE_2 = 32, // 78
  ADE_SIZE_AVRMSONE_2 = 32, // 78
  ADE_SIZE_AIRMS1012_2 = 32, // 78
  ADE_SIZE_AVRMS1012_2 = 32, // 78
  ADE_SIZE_BV_PCF_2 = 32,
  ADE_SIZE_BI_PCF_2 = 32,
  ADE_SIZE_BIRMS_2 = 32,
  ADE_SIZE_BVRMS_2 = 32,
  ADE_SIZE_BWATT_2 = 32,
  ADE_SIZE_BVA_2 = 32,
  ADE_SIZE_BVAR_2 = 32,
  ADE_SIZE_BFVAR_2 = 32,
  ADE_SIZE_BPF_2 = 32,
  ADE_SIZE_BVTHD_2 = 32, // 78
  ADE_SIZE_BITHD_2 = 32, // 78
  ADE_SIZE_BFWATT_2 = 32, // 78
  ADE_SIZE_BFVA_2 = 32, // 78
  ADE_SIZE_BFIRMS_2 = 32, // 78
  ADE_SIZE_BFVRMS_2 = 32, // 78
  ADE_SIZE_BIRMSONE_2 = 32, // 78
  ADE_SIZE_BVRMSONE_2 = 32, // 78
  ADE_SIZE_BIRMS1012_2 = 32, // 78
  ADE_SIZE_BVRMS1012_2 = 32, // 78
  ADE_SIZE_CV_PCF_2 = 32,
  ADE_SIZE_CI_PCF_2 = 32,
  ADE_SIZE_CIRMS_2 = 32,
  ADE_SIZE_CVRMS_2 = 32,
  ADE_SIZE_CWATT_2 = 32,
  ADE_SIZE_CVA_2 = 32,
  ADE_SIZE_CVAR_2 = 32,
  ADE_SIZE_CFVAR_2 = 32,
  ADE_SIZE_CPF_2 = 32,
  ADE_SIZE_CVTHD_2 = 32, // 78
  ADE_SIZE_CITHD_2 = 32, // 78
  ADE_SIZE_CFWATT_2 = 32, // 78
  ADE_SIZE_CFVA_2 = 32, // 78
  ADE_SIZE_CFIRMS_2 = 32, // 78
  ADE_SIZE_CFVRMS_2 = 32, // 78
  ADE_SIZE_CIRMSONE_2 = 32, // 78
  ADE_SIZE_CVRMSONE_2 = 32, // 78
  ADE_SIZE_CIRMS1012_2 = 32, // 78
  ADE_SIZE_CVRMS1012_2 = 32, // 78
  ADE_SIZE_NI_PCF_2 = 32,
  ADE_SIZE_NIRMS_2 = 32,
  ADE_SIZE_NIRMSONE_2 = 32, // 78
  ADE_SIZE_NIRMS1012_2 = 32 // 78
};

enum
RegisterStartBit
{
  // IF YOUR REGISTER NAME IS NOT HERE PASS THIS PARAMETER:
  ADE_SB_FULL = 0,
  // ADE_ADD_CONFIG0
  ADE_SB_DISRPLPF = 13,
  ADE_SB_DISAPLPF = 12,
  ADE_SB_ININTEN = 11,
  ADE_SB_VNOMC_EN = 10,
  ADE_SB_VNOMB_EN = 9,
  ADE_SB_VNOMA_EN = 8,
  ADE_SB_ZX_SRC_SEL = 6,
  ADE_SB_INTEN = 5,
  ADE_SB_MTEN = 4,
  ADE_SB_HPFDIS = 3,
  ADE_SB_ISUM_CFG = 0,
  // ADE_ADD_AMTREGION
  ADE_SB_AREGION = 0,
  // ADE_ADD_BMTREGION
  ADE_SB_BREGION = 0,
  // ADE_ADD_CMTREGION
  ADE_SB_CREGION = 0,
  // ADE_ADD_IPEAK
  ADE_SB_IPPHASE = 24,
  ADE_SB_IPEAKVAL = 0,
  // ADE_ADD_VPEAK
  ADE_SB_VPPHASE = 24,
  ADE_SB_VPEAKVAL = 0,
  // ADE_ADD_STATUS0 & ADE_ADD_MASK0
  ADE_SB_MISMTCH = 24,
  ADE_SB_COH_WFB_FULL = 23,
  ADE_SB_WFB_TRIG = 22,
  ADE_SB_PF_RDY = 21,
  ADE_SB_PWRRDY = 18,
  ADE_SB_PAGE_FULL = 14,
  ADE_SB_WFB_TRIG_IRQ = 16,
  ADE_SB_DREADY = 15,
  ADE_SB_CF4 = 14,
  ADE_SB_CF3 = 13,
  ADE_SB_CF2 = 12,
  ADE_SB_CF1 = 11,
  ADE_SB_REVPSUM4 = 10,
  ADE_SB_REVPSUM3 = 9,
  ADE_SB_REVPSUM2 = 8,
  ADE_SB_REVPSUM1 = 7,
  ADE_SB_REVRPC = 6,
  ADE_SB_REVRPB = 5,
  ADE_SB_REVRPA = 4,
  ADE_SB_REVAPC = 3,
  ADE_SB_REVAPB = 2,
  ADE_SB_REVAPA = 1,
  ADE_SB_EGYRDY = 0,
  // ADE_ADD_STATUS1 & ADE_ADD_MASK1
  ADE_SB_ERROR3 = 31,
  ADE_SB_ERROR2 = 30,
  ADE_SB_ERROR1 = 29,
  ADE_SB_ERROR0 = 28,
  ADE_SB_CRC_DONE = 27,
  ADE_SB_CRC_CHG = 26,
  ADE_SB_SEQERR = 18,
  ADE_SB_RSTDONE = 16,
  ADE_SB_ZXIC = 15,
  ADE_SB_ZXIB = 14,
  ADE_SB_ZXIA = 13,
  ADE_SB_ZXCOMB = 12,
  ADE_SB_ZXVC = 11,
  ADE_SB_ZXVB = 10,
  ADE_SB_ZXVA = 9,
  ADE_SB_ZXTOVC = 8,
  ADE_SB_ZXTOVB = 7,
  ADE_SB_ZXTOVA = 6,
  ADE_SB_RFNOLOAD = 4,
  ADE_SB_VANLOAD = 2,
  ADE_SB_RNLOAD = 1,
  ADE_SB_ANLOAD = 0,
  // ADE_ADD_EVENT_STATUS & ADE_ADD_EVENT_MASK
  ADE_SB_E_DREADY = 16,
  ADE_SB_E_RFNOLOAD = 14,
  ADE_SB_E_VANLOAD = 12,
  ADE_SB_E_RNLOAD = 11,
  ADE_SB_E_ANLOAD = 10,
  ADE_SB_E_REVPSUM4 = 9,
  ADE_SB_E_REVPSUM3 = 8,
  ADE_SB_E_REVPSUM2 = 7,
  ADE_SB_E_REVPSUM1 = 6,
  // ADE_ADD_VLEVEL
  ADE_SB_VLEVEL_VAL = 0,
  // ADE_PHNOLOAD
  ADE_SB_CFVARNL = 16,
  ADE_SB_CVANL = 14,
  ADE_SB_CVARNL = 13,
  ADE_SB_CWATTNL = 12,
  ADE_SB_BFVARNL = 10,
  ADE_SB_BVANL = 8,
  ADE_SB_BVARNL = 7,
  ADE_SB_BWATTNL = 6,
  ADE_SB_AFVARNL = 4,
  ADE_SB_AVANL = 2,
  ADE_SB_AVARNL = 1,
  ADE_SB_AWATTNL = 0,
  // ADE_ADD_ADC_REDIRECT
  ADE_SB_VC_DIN = 18,
  ADE_SB_VB_DIN = 15,
  ADE_SB_VA_DIN = 12,
  ADE_SB_IN_DIN = 9,
  ADE_SB_IC_DIN = 6,
  ADE_SB_IB_DIN = 3,
  ADE_SB_IA_DIN = 0,
  // ADE_ADD_CF_LCFG
  ADE_SB_CF4_LT = 22,
  ADE_SB_CF3_LT = 21,
  ADE_SB_CF2_LT = 20,
  ADE_SB_CF1_LT = 19,
  ADE_SB_CF_LTMR = 0,
  // ADE_ADD_PART_ID [IT HAS PROBLEM]
  // ADE_ADD_CONFIG1
  ADE_SB_EXT_REF = 15,
  ADE_SB_IRQ0_ON_IRQ1 = 12,
  ADE_SB_BURST_EN = 11,
  ADE_SB_PWR_SETTLE = 8,
  ADE_SB_CF_ACC_CLR = 5,
  ADE_SB_CF4_CFG = 2,
  ADE_SB_CF3_CFG = 1,
  ADE_SB_SWRST = 0,
  // ADE_ADD_CFMODE
  ADE_SB_CF4DIS = 15,
  ADE_SB_CF3DIS = 14,
  ADE_SB_CF2DIS = 13,
  ADE_SB_CF1DIS = 12,
  ADE_SB_CF4SEL = 9,
  ADE_SB_CF3SEL = 6,
  ADE_SB_CF2SEL = 3,
  ADE_SB_CF1SEL = 0,
  // ADE_ADD_COMPMODE
  ADE_SB_TERMSEL4 = 9,
  ADE_SB_TERMSEL3 = 6,
  ADE_SB_TERMSEL2 = 3,
  ADE_SB_TERMSEL1 = 0,
  // ADE_ADD_ACCMODE
  ADE_SB_SELFREQ = 8,
  ADE_SB_ICONSEL = 7,
  ADE_SB_VCONSEL = 4,
  ADE_SB_VARACC = 2,
  ADE_SB_WATTACC = 0,
  // ADE_ADD_CONFIG3
  ADE_SB_PEAKSEL = 2,
  // ADE_ADD_ZX_LP_SEL
  ADE_SB_LP_SEL = 3,
  ADE_SB_ZX_SEL = 1,
  // ADE_ADD_PHSIGN
  ADE_SB_SUM4SIGN = 9,
  ADE_SB_SUM3SIGN = 8,
  ADE_SB_SUM2SIGN = 7,
  ADE_SB_SUM1SIGN = 6,
  ADE_SB_CVARSIGN = 5,
  ADE_SB_CWSIGN = 4,
  ADE_SB_BVARSIGN = 3,
  ADE_SB_BWSIGN = 2,
  ADE_SB_AVARSIGN = 1,
  ADE_SB_AWSIGN = 0,
  // ADE_ADD_WFB_CFG
  ADE_SB_WF_IN_EN = 12,
  ADE_SB_WF_SRC = 8,
  ADE_SB_WF_MODE = 6,
  ADE_SB_WF_CAP_SEL = 5,
  ADE_SB_WF_CAP_EN = 4,
  ADE_SB_BURST_CHAN = 0,
  // ADE_ADD_WFB_TRG_CFG
  ADE_SB_TR_TRIG_FORCE = 10,
  ADE_SB_TR_ZXCOMB = 9,
  ADE_SB_TR_ZXVC = 8,
  ADE_SB_TR_ZXVB = 7,
  ADE_SB_TR_ZXVA = 6,
  ADE_SB_TR_ZXIC = 5,
  ADE_SB_TR_ZXIB = 4,
  ADE_SB_TR_ZXIA = 3,
  // ADE_ADD_WFB_TRG_STAT
  ADE_SB_WFB_LAST_PAGE = 12,
  ADE_SB_WFB_TRIG_ADDR = 0,
  // ADE_ADD_CONFIG2
  ADE_SB_UPERIOD_SEL = 12,
  ADE_SB_HPF_CRN = 9,
  // ADE_ADD_EP_CFG
  ADE_SB_NOLOAD_TMR = 13,
  ADE_SB_PWR_SIGN_SEL = 7,
  ADE_SB_RD_RST_EN = 5,
  ADE_SB_EGY_LD_ACCUM = 4,
  ADE_SB_EGY_TMR_MODE = 1,
  ADE_SB_EGY_PWR_EN = 0,
  // ADE_ADD_CRC_FORCE
  ADE_SB_FORCE_CRC_UPDATE = 0,
  // ADE_ADD_CRC_OPTEN
  ADE_SB_CRC_WFB_TRG_CFG_EN = 15,
  ADE_SB_CRC_WFB_PG_IRQEN = 14,
  ADE_SB_CRC_WFB_CFG_EN = 13,
  ADE_SB_CRC_SEQ_CYC_EN = 12,
  ADE_SB_CRC_ZXLPSEL_EN = 11,
  ADE_SB_CRC_ZXTOUT_EN = 10,
  ADE_SB_CRC_APP_NL_LVL_EN = 9,
  ADE_SB_CRC_REACT_NL_LVL_EN = 8,
  ADE_SB_CRC_ACT_NL_LVL_EN = 7,
  ADE_SB_CRC_EVENT_MASK_EN = 2,
  ADE_SB_CRC_MASK1_EN = 1,
  ADE_SB_CRC_MASK0_EN = 0,
  // ADE_ADD_PSM2_CFG
  ADE_SB_PKDET_LVL = 5,
  ADE_SB_LPLINE = 0,
  // ADE_ADD_PGA_GAIN
  ADE_SB_VC_GAIN = 12,
  ADE_SB_VB_GAIN = 10,
  ADE_SB_VA_GAIN = 8,
  ADE_SB_IN_GAIN = 6,
  ADE_SB_IC_GAIN = 4,
  ADE_SB_IB_GAIN = 2,
  ADE_SB_IA_GAIN = 0,
  // ADE_ADD_CHNL_DIS
  ADE_SB_VC_DISADC = 6,
  ADE_SB_VB_DISADC = 5,
  ADE_SB_VA_DISADC = 4,
  ADE_SB_IN_DISADC = 3,
  ADE_SB_IC_DISADC = 2,
  ADE_SB_IB_DISADC = 1,
  ADE_SB_IA_DISADC = 0,
  // ADE_ADD_VAR_DIS
  ADE_SB_VARDIS = 0
};

enum
RegisterMaskBit
{
  // IF YOUR REGISTER NAME IS NOT HERE PASS THIS PARAMETER:
  ADE_MB_FULL = 0xFFFFFFFF,
  // ADE_ADD_CONFIG0
  ADE_MB_DISRPLPF = 1,
  ADE_MB_DISAPLPF = 1,
  ADE_MB_ININTEN = 1,
  ADE_MB_VNOMC_EN = 1,
  ADE_MB_VNOMB_EN = 1,
  ADE_MB_VNOMA_EN = 1,
  ADE_MB_ZX_SRC_SEL = 1,
  ADE_MB_INTEN = 1,
  ADE_MB_MTEN = 1,
  ADE_MB_HPFDIS = 1,
  ADE_MB_ISUM_CFG = 3,
  // ADE_ADD_AMTREGION
  ADE_MB_AREGION = 0xF,
  // ADE_ADD_BMTREGION
  ADE_MB_BREGION = 0xF,
  // ADE_ADD_CMTREGION
  ADE_MB_CREGION = 0xF,
  // ADE_ADD_IPEAK
  ADE_MB_IPPHASE = 7,
  ADE_MB_IPEAKVAL = 0xFFFFFF,
  // ADE_ADD_VPEAK
  ADE_MB_VPPHASE = 7,
  ADE_MB_VPEAKVAL = 0xFFFFFF,
  // ADE_ADD_STATUS0 & ADE_ADD_MASK0
  ADE_MB_MISMTCH = 1,
  ADE_MB_COH_WFB_FULL = 1,
  ADE_MB_WFB_TRIG = 1,
  ADE_MB_PF_RDY = 1,
  ADE_MB_PWRRDY = 1,
  ADE_MB_PAGE_FULL = 1,
  ADE_MB_WFB_TRIG_IRQ = 1,
  ADE_MB_DREADY = 1,
  ADE_MB_CF4 = 1,
  ADE_MB_CF3 = 1,
  ADE_MB_CF2 = 1,
  ADE_MB_CF1 = 1,
  ADE_MB_REVPSUM4 = 1,
  ADE_MB_REVPSUM3 = 1,
  ADE_MB_REVPSUM2 = 1,
  ADE_MB_REVPSUM1 = 1,
  ADE_MB_REVRPC = 1,
  ADE_MB_REVRPB = 1,
  ADE_MB_REVRPA = 1,
  ADE_MB_REVAPC = 1,
  ADE_MB_REVAPB = 1,
  ADE_MB_REVAPA = 1,
  ADE_MB_EGYRDY = 1,
  // ADE_ADD_STATUS1 & ADE_ADD_MASK1
  ADE_MB_ERROR3 = 1,
  ADE_MB_ERROR2 = 1,
  ADE_MB_ERROR1 = 1,
  ADE_MB_ERROR0 = 1,
  ADE_MB_CRC_DONE = 1,
  ADE_MB_CRC_CHG = 1,
  ADE_MB_SEQERR = 1,
  ADE_MB_RSTDONE = 1,
  ADE_MB_ZXIC = 1,
  ADE_MB_ZXIB = 1,
  ADE_MB_ZXIA = 1,
  ADE_MB_ZXCOMB = 1,
  ADE_MB_ZXVC = 1,
  ADE_MB_ZXVB = 1,
  ADE_MB_ZXVA = 1,
  ADE_MB_ZXTOVC = 1,
  ADE_MB_ZXTOVB = 1,
  ADE_MB_ZXTOVA = 1,
  ADE_MB_RFNOLOAD = 1,
  ADE_MB_VANLOAD = 1,
  ADE_MB_RNLOAD = 1,
  ADE_MB_ANLOAD = 1,
  // ADE_ADD_EVENT_STATUS & ADE_ADD_EVENT_MASK
  ADE_MB_E_DREADY = 1,
  ADE_MB_E_RFNOLOAD = 1,
  ADE_MB_E_VANLOAD = 1,
  ADE_MB_E_RNLOAD = 1,
  ADE_MB_E_ANLOAD = 1,
  ADE_MB_E_REVPSUM4 = 1,
  ADE_MB_E_REVPSUM3 = 1,
  ADE_MB_E_REVPSUM2 = 1,
  ADE_MB_E_REVPSUM1 = 1,
  // ADE_ADD_VLEVEL
  ADE_MB_VLEVEL_VAL = 0xFFFFFF,
  // ADE_PHNOLOAD
  ADE_MB_CFVARNL = 1,
  ADE_MB_CVANL = 1,
  ADE_MB_CVARNL = 1,
  ADE_MB_CWATTNL = 1,
  ADE_MB_BFVARNL = 1,
  ADE_MB_BVANL = 1,
  ADE_MB_BVARNL = 1,
  ADE_MB_BWATTNL = 1,
  ADE_MB_AFVARNL = 1,
  ADE_MB_AVANL = 1,
  ADE_MB_AVARNL = 1,
  ADE_MB_AWATTNL = 1,
  // ADE_ADD_ADC_REDIRECT
  ADE_MB_VC_DIN = 7,
  ADE_MB_VB_DIN = 7,
  ADE_MB_VA_DIN = 7,
  ADE_MB_IN_DIN = 7,
  ADE_MB_IC_DIN = 7,
  ADE_MB_IB_DIN = 7,
  ADE_MB_IA_DIN = 7,
  // ADE_ADD_CF_LCFG
  ADE_MB_CF4_LT = 1,
  ADE_MB_CF3_LT = 1,
  ADE_MB_CF2_LT = 1,
  ADE_MB_CF1_LT = 1,
  ADE_MB_CF_LTMR = 0x7FFFF,
  // ADE_ADD_PART_ID [IT HAS PROBLEM, DO NOT USE IT]
  // ADE_ADD_CONFIG1
  ADE_MB_EXT_REF = 1,
  ADE_MB_IRQ0_ON_IRQ1 = 1,
  ADE_MB_BURST_EN = 1,
  ADE_MB_PWR_SETTLE = 3,
  ADE_MB_CF_ACC_CLR = 1,
  ADE_MB_CF4_CFG = 3,
  ADE_MB_CF3_CFG = 1,
  ADE_MB_SWRST = 1,
  // ADE_ADD_CFMODE
  ADE_MB_CF4DIS = 1,
  ADE_MB_CF3DIS = 1,
  ADE_MB_CF2DIS = 1,
  ADE_MB_CF1DIS = 1,
  ADE_MB_CF4SEL = 1,
  ADE_MB_CF3SEL = 1,
  ADE_MB_CF2SEL = 1,
  ADE_MB_CF1SEL = 1,
  // ADE_ADD_COMPMODE
  ADE_MB_TERMSEL4 = 7,
  ADE_MB_TERMSEL3 = 7,
  ADE_MB_TERMSEL2 = 7,
  ADE_MB_TERMSEL1 = 7,
  // ADE_ADD_ACCMODE
  ADE_MB_SELFREQ = 1,
  ADE_MB_ICONSEL = 1,
  ADE_MB_VCONSEL = 3,
  ADE_MB_VARACC = 3,
  ADE_MB_WATTACC = 3,
  // ADE_ADD_CONFIG3
  ADE_MB_PEAKSEL = 7,
  // ADE_ADD_ZX_LP_SEL
  ADE_MB_LP_SEL = 3,
  ADE_MB_ZX_SEL = 3,
  // ADE_ADD_PHSIGN
  ADE_MB_SUM4SIGN = 1,
  ADE_MB_SUM3SIGN = 1,
  ADE_MB_SUM2SIGN = 1,
  ADE_MB_SUM1SIGN = 1,
  ADE_MB_CVARSIGN = 1,
  ADE_MB_CWSIGN = 1,
  ADE_MB_BVARSIGN = 1,
  ADE_MB_BWSIGN = 1,
  ADE_MB_AVARSIGN = 1,
  ADE_MB_AWSIGN = 1,
  // ADE_ADD_WFB_CFG
  ADE_MB_WF_IN_EN = 1,
  ADE_MB_WF_SRC = 3,
  ADE_MB_WF_MODE = 3,
  ADE_MB_WF_CAP_SEL = 1,
  ADE_MB_WF_CAP_EN = 1,
  ADE_MB_BURST_CHAN = 0xF,
  // ADE_ADD_WFB_TRG_CFG
  ADE_MB_TR_TRIG_FORCE = 1,
  ADE_MB_TR_ZXCOMB = 1,
  ADE_MB_TR_ZXVC = 1,
  ADE_MB_TR_ZXVB = 1,
  ADE_MB_TR_ZXVA = 1,
  ADE_MB_TR_ZXIC = 1,
  ADE_MB_TR_ZXIB = 1,
  ADE_MB_TR_ZXIA = 1,
  // ADE_ADD_WFB_TRG_STAT
  ADE_MB_WFB_LAST_PAGE = 0xF,
  ADE_MB_WFB_TRIG_ADDR = 0x7FF,
  // ADE_ADD_CONFIG2
  ADE_MB_UPERIOD_SEL = 1,
  ADE_MB_HPF_CRN = 7,
  // ADE_ADD_EP_CFG
  ADE_MB_NOLOAD_TMR = 7,
  ADE_MB_PWR_SIGN_SEL = 1,
  ADE_MB_RD_RST_EN = 1,
  ADE_MB_EGY_LD_ACCUM = 1,
  ADE_MB_EGY_TMR_MODE = 1,
  ADE_MB_EGY_PWR_EN = 1,
  // ADE_ADD_CRC_FORCE
  ADE_MB_FORCE_CRC_UPDATE = 1,
  // ADE_ADD_CRC_OPTEN
  ADE_MB_CRC_WFB_TRG_CFG_EN = 1,
  ADE_MB_CRC_WFB_PG_IRQEN = 1,
  ADE_MB_CRC_WFB_CFG_EN = 1,
  ADE_MB_CRC_SEQ_CYC_EN = 1,
  ADE_MB_CRC_ZXLPSEL_EN = 11,
  ADE_MB_CRC_ZXTOUT_EN = 1,
  ADE_MB_CRC_APP_NL_LVL_EN = 1,
  ADE_MB_CRC_REACT_NL_LVL_EN = 1,
  ADE_MB_CRC_ACT_NL_LVL_EN = 1,
  ADE_MB_CRC_EVENT_MASK_EN = 1,
  ADE_MB_CRC_MASK1_EN = 1,
  ADE_MB_CRC_MASK0_EN = 1,
  // ADE_ADD_PSM2_CFG
  ADE_MB_PKDET_LVL = 0xF,
  ADE_MB_LPLINE = 0x1F,
  // ADE_ADD_PGA_GAIN
  ADE_MB_VC_GAIN = 3,
  ADE_MB_VB_GAIN = 3,
  ADE_MB_VA_GAIN = 3,
  ADE_MB_IN_GAIN = 3,
  ADE_MB_IC_GAIN = 3,
  ADE_MB_IB_GAIN = 3,
  ADE_MB_IA_GAIN = 3,
  // ADE_ADD_CHNL_DIS
  ADE_MB_VC_DISADC = 1,
  ADE_MB_VB_DISADC = 1,
  ADE_MB_VA_DISADC = 1,
  ADE_MB_IN_DISADC = 1,
  ADE_MB_IC_DISADC = 1,
  ADE_MB_IB_DISADC = 1,
  ADE_MB_IA_DISADC = 1,
  // ADE_ADD_VAR_DIS
  ADE_MB_VARDIS = 1
};

#endif